### ISSUE TITLE
Looping Read macro

### ISSUE THREAD

**Issue by GekoGpose** [maributt/OldMacroRecursion#1]
Was working the day prior to this but now it's not? 
/micon "read" emote
/read <wait.11>
/runmacro 2 Individual

is the macro im running trying to just /read while I afk and addon is updated am I doing something wrong here? 

the error im getting is 
The command /runmacro 2 Individual does not exist.

**Comment by maributt** [comment]
This is because there was an API bump sometime around the time you started noticing this I believe?
Anyways the plugin should be fixed and working as expected now!
You can install it from `https://raw.githubusercontent.com/maributt/xivplugins/main/repo.json`
